site_name: MultiRoute Go!

nav:
    - Home: index.md
    - Handbuch:
      - Übersicht: uebersicht.md
      - Aufbau: aufbau.md
      - 1. Datenintegration: upload.md
      - 2. Gebietsplanung: gebietsplanung.md
      - 3. Adressverwaltung: adressverwaltung.md
      - 4. Spezialhäuser: spezialhaeuser.md
      - 5. Gehfolgenberechnung: gehfolgen.md
      - 6. Zusatzmodule: zusatzmodule.md
      - 7. Exporte: exporte.md
 #      - Tipps & Tricks: tipps.md
      - Webinare: webinare.md

    - API:
      - MRG! API: api-intro.md
      - Routen & Endpunkte: routen.md

#    - Referenzen: 14.md
#    - Preise: preise.md
    - Impressum: impressum.md
    - Datenschutz: datenschutz.md

theme:
  name: material
  custom_dir: docs/theme_override_home/
  # 404 page
  static_templates:
    - 404.html
  # enable light/dark mode
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    
  font:
    text: Roboto
    code: Roboto Mono
  icon:  # from .icons path. Add to theme override for custom logo.
    logo: Briefkasten  # top left header logo
    repo: fontawesome/brands/git-alt
  favicon: assets/favicon.ico #browser tab logo

extra_javascript:
        - 'stylesheets/extra.js'
extra_css:
        - stylesheets/extra.css
        - stylesheets/font-awesome-4.7.0/css/font-awesome.min.css

repo_url: https://github.com/gbconsite/MultiRoute-Go
repo_name: gbconsite/MultiRoute-Go
edit_uri: ./edit/main/docs

markdown_extensions:
  - lightgallery
  - attr_list
  - md_in_html # enable lazy loading images via ![!](assets/Auftragsinfos.jpg){ loading=lazy }
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.toc:
      baselevel: 1
      permalink: true
  - toc:
      title: Inhalt
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      
plugins:
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
